version: '3.3'

services:
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.dev
    env_file: .env
    command: mix phx.server
    environment:
      - "USER=${USER}"
    ports:
      - "${CODEBATTLE_PORT}:${CODEBATTLE_PORT}"
    volumes:
      - "./services/app:/app:cached"
      - "~/.bash_history:/root/.bash_history:cached"
      - ".bashrc:/root/.bashrc:cached"
      - '/var/run/docker.sock:/var/run/docker.sock:cached'
      - "/var/tmp:/var/tmp:cached"
      - "/tmp:/tmp:cached"
    depends_on:
      - db

  db:
    image: postgres:10
    environment:
      POSTGRES_USER: ${CODEBATTLE_DB_USERNAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
     - 5432:5432

volumes:
  pg_data:
